# Generated by Django 3.2.3 on 2021-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
