# Generated by Django 3.2.3 on 2021-06-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='description',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='location',
        ),
    ]
